'use client';
import Link from 'next/link'; import { useParams } from 'next/navigation'; import { useEffect, useState, type FormEvent } from 'react';
import { useAuth } from '@/hooks/useAuth'; import { confirmSupportResolved, getSupportMessages, getSupportTicket, rateSupport, sendSupportMessage } from '@/lib/support-api'; import type { SupportMessage, SupportTicket } from '@/lib/types';
const label = (v: string) => v.replaceAll('_',' ').replace(/\b\w/g,(c)=>c.toUpperCase());
export default function SupportThreadPage() { const { id } = useParams<{id:string}>(); const { token, user } = useAuth(); const [ticket,setTicket]=useState<SupportTicket|null>(null); const [messages,setMessages]=useState<SupportMessage[]>([]); const [body,setBody]=useState(''); const [rating,setRating]=useState(5);
  const load=()=>{if(token) Promise.all([getSupportTicket(token,id),getSupportMessages(token,id)]).then(([t,m])=>{setTicket(t);setMessages(m);});}; useEffect(load,[token,id]);
  async function reply(e:FormEvent){e.preventDefault();if(!token||!body.trim())return;const m=await sendSupportMessage(token,id,body.trim());setMessages((x)=>[...x,m]);setBody('');}
  if(!ticket)return <main className="mx-auto max-w-3xl p-6">Loading support request…</main>;
  return <main className="mx-auto max-w-3xl space-y-5 px-4 py-8"><Link href="/account/support" className="text-sm text-brand-700">← All support requests</Link><header className="rounded-2xl bg-brand-900 p-5 text-white"><div className="flex justify-between gap-3"><div><p className="text-xs text-white/70">{ticket.reference}</p><h1 className="text-xl font-bold">{ticket.subject}</h1></div><span className="h-fit rounded-full bg-white/15 px-3 py-1 text-xs font-semibold">{label(ticket.status)}</span></div><p className="mt-3 whitespace-pre-wrap text-sm text-white/80">{ticket.description}</p>{ticket.attachments.length>0&&<div className="mt-3 flex gap-2">{ticket.attachments.map((x)=><a key={x} href={x} target="_blank"><img src={x} alt="Ticket attachment" className="h-20 w-20 rounded-lg object-cover"/></a>)}</div>}</header>
  <section aria-label="Conversation" className="min-h-60 space-y-3 rounded-2xl border p-4 dark:border-slate-800">{messages.length===0&&<p className="text-center text-sm text-slate-500">A support agent will respond here.</p>}{messages.map((m)=><div key={m.id} className={`flex ${m.senderUserId===user?.id?'justify-end':'justify-start'}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm ${m.senderUserId===user?.id?'bg-brand-700 text-white':'bg-slate-100 dark:bg-slate-800'}`}><p className="whitespace-pre-wrap">{m.body}</p><p className="mt-1 text-[10px] opacity-70">{m.senderUserId===user?.id?'You':'Support'} · {new Date(m.createdAt).toLocaleString()}</p></div></div>)}</section>
  {ticket.status!=='closed'&&<form onSubmit={reply} className="flex gap-2"><textarea aria-label="Reply" required value={body} onChange={(e)=>setBody(e.target.value)} rows={2} className="min-w-0 flex-1 rounded-xl border p-3 dark:bg-slate-900" placeholder="Write a reply…"/><button className="rounded-xl bg-brand-700 px-5 font-semibold text-white">Send</button></form>}
  {ticket.status==='resolved'&&<button onClick={async()=>{if(token)setTicket(await confirmSupportResolved(token,id));}} className="rounded-full bg-emerald-700 px-4 py-2 font-semibold text-white">Confirm this is resolved</button>}
  {(ticket.status==='resolved'||ticket.status==='closed')&&ticket.rating===null&&<div className="rounded-2xl border p-4 dark:border-slate-800"><p className="font-semibold">Rate your support experience</p><div className="mt-2 flex items-center gap-3"><select value={rating} onChange={(e)=>setRating(Number(e.target.value))} className="rounded-lg border p-2 dark:bg-slate-900">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} star{n===1?'':'s'}</option>)}</select><button onClick={async()=>{if(token)setTicket(await rateSupport(token,id,rating));}} className="rounded-full bg-brand-700 px-4 py-2 text-sm font-semibold text-white">Submit rating</button></div></div>}
  </main>; }
